<a href="https://colab.research.google.com/github/Noreen999/AI-and-Data-Science/blob/main/Module_2_maths_and_statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy in python

How to define matrix and vector in Python with NumPy

In [ ]:
pip install ucimlrepo


In [ ]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
iris = fetch_ucirepo(id=53)

# data (as pandas dataframes)
X = iris.data.features
y = iris.data.targets




In [ ]:
import numpy as np
import pandas as pd

a= np.arange(6)

a2=a[np.newaxis, :]
a2
# (1,6)


array([[0, 1, 2, 3, 4, 5]])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a=np.arange(6)
a2=a[np.newaxis, :]
a2.shape

(1, 6)

SyntaxError: ignored

In [ ]:
import numpy as np


In [ ]:
x=np.array([[1,2,3],[4,5,6]])
x.shape

(2, 3)

In [ ]:
x[:,0]# 0th column

array([1, 4])

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x[:1,:]# 1th row


array([[1, 2, 3]])

In [ ]:
x=np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
x= np.arange(5)# Create array
x

array([0, 1, 2, 3, 4])

In [ ]:
x=np.array([[1,2,3,4],[1,2,3,4]])
print('x:\n{}'.format(x))


x:
[[1 2 3 4]
 [1 2 3 4]]


Using loop

In [ ]:
a = np.array([1,2,3,4,5])

squared= []

for i in a:
   squared.append(i ** 2)
print("Squared values using a for loop:", squared)



Squared values using a for loop: [1, 4, 9, 16, 25]


Vectoriztion

In [ ]:
squared = a ** 2

print("Squared values using vectorized operation:", squared)

Squared values using vectorized operation: [ 1  4  9 16 25]


Broadcasting

In [ ]:
import numpy as np

A = np.arange(32).reshape(4, 1, 8)

A

array([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29, 30, 31]]])

In [ ]:
df='/content/sample_data/california_housing_train.csv'

In [ ]:
df

'/content/sample_data/california_housing_train.csv'

In [ ]:
type(df)

str

In [ ]:
data=np.loadtxt('/content/sample_data/california_housing_train.csv', delimiter=',', dtype=str)
display(data)

array([['"longitude"', '"latitude"', '"housing_median_age"', ...,
        '"households"', '"median_income"', '"median_house_value"'],
       ['-114.310000', '34.190000', '15.000000', ..., '472.000000',
        '1.493600', '66900.000000'],
       ['-114.470000', '34.400000', '19.000000', ..., '463.000000',
        '1.820000', '80100.000000'],
       ...,
       ['-124.300000', '41.840000', '17.000000', ..., '456.000000',
        '3.031300', '103600.000000'],
       ['-124.300000', '41.800000', '19.000000', ..., '478.000000',
        '1.979700', '85800.000000'],
       ['-124.350000', '40.540000', '52.000000', ..., '270.000000',
        '3.014700', '94600.000000']], dtype='<U20')

In [ ]:
data.shape

(17001, 9)

In [ ]:
import pandas as pd
df=pd.read_csv('/content/sample_data/california_housing_train.csv')

In [ ]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [ ]:
df.shape

(17000, 9)

In [ ]:
df.size

153000

In [ ]:
df = df.drop(columns=['latitude'])

In [ ]:
df.to_csv('data.csv', index=False)
df

longitude  housing_median_age  total_rooms  total_bedrooms  population  \
0        -114.31                15.0       5612.0          1283.0      1015.0   
1        -114.47                19.0       7650.0          1901.0      1129.0   
2        -114.56                17.0        720.0           174.0       333.0   
3        -114.57                14.0       1501.0           337.0       515.0   
4        -114.57                20.0       1454.0           326.0       624.0   
...          ...                 ...          ...             ...         ...   
16995    -124.26                52.0       2217.0           394.0       907.0   
16996    -124.27                36.0       2349.0           528.0      1194.0   
16997    -124.30                17.0       2677.0           531.0      1244.0   
16998    -124.30                19.0       2672.0           552.0      1298.0   
16999    -124.35                52.0       1820.0           300.0       806.0   

       households  median_income  median_house_value  
0           472.0         1.4936             66900.0  
1           463.0         1.8200             80100.0  
2           117.0         1.6509             85700.0  
3           226.0         3.1917             73400.0  
4           262.0         1.9250             65500.0  
...           ...            ...                 ...  
16995       369.0         2.3571            111400.0  
16996       465.0         2.5179             79000.0  
16997       456.0         3.0313            103600.0  
16998       478.0         1.9797             85800.0  
16999       270.0         3.0147             94600.0  

[17000 rows x 8 columns]

In [ ]:
df['longitude']

0       -114.31
1       -114.47
2       -114.56
3       -114.57
4       -114.57
          ...  
16995   -124.26
16996   -124.27
16997   -124.30
16998   -124.30
16999   -124.35
Name: longitude, Length: 17000, dtype: float64